# left-side user profile
avatar: /avatar/provenr.jpg
location: BeiJing,China
email: web_lyn@163.com
social:
  github: https://provenr.github.io/
  weibo:
  linkedin:

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: e56a1706ae9d773852a4a03368b51f86
duoshuo: # duoshuo username
gsc: # google custom search code



