language: node_js  #设置語言

node_js: stable  # 设置node 版本
cache:
  apt: true
  directories:
    - node_modules # 緩存不經常更改的內容

git:
  submodules: false

before_install:
  - npm install hexo-cli -g

install:
  # - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - npm install

before_script:
  - echo 正在清空缓存静态文件...
  - hexo clean                      # 清除缓存静态文件
  - echo 正在生成静态文件...
  - hexo g                          # 生成静态文件

script:
  - echo 开始部署...
  - cd ./public
  - git init
  - git config --global user.name "${GH_username}"                          # 修改name
  - git config --global user.email "${GH_useremail}"                        # 修改email
  - git add .
  - git commit -m "update blog content by travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  # GH_TOKEN是在Travis中配置github 中的token

after_script:
  - echo 部署完成！

branches:
  only:
    - master              # 只监控master分支，可根据自己情况设置
env:
  global:
    - GH_REF: github.com/Provenr/Provenr.github.io.git       # 设置 github 项目仓库地址
    - GH_username: liuyangning                          # 设置 github 用户名
    - GH_useremail: web_lyn@163.com