language: node_js
node_js:
- 12
cache:
  apt: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_f31094380f4c_key -iv $encrypted_f31094380f4c_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host ${G_HOST}\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa"
  >> ~/.ssh/config

install:
- npm install hexo -g
- echo 安装hexo相关环境
- npm install
before_script:
- echo 正在清空缓存静态文件...
- hexo clean
- echo 正在生成静态文件...
- hexo generate
- cd ./public
- ls -l
script:
- echo 开始部署...
- git init
- git config --global user.name "${GH_username}"
- git config --global user.email "${GH_useremail}"
- git add .
- git commit -m "update auto by travis CI"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
after_script:
- echo 部署完成！
branches:
  only:
  - master
env:
  global:
  - GH_REF=github.com/Provenr/Provenr.github.io.git
  - GH_username=liuyangning
  - GH_useremail=web_lyn@163.com
  - G_HOST=119.3.215.227
after_success:
  - cd ./public/
  - echo 准备移动至指定文件夹到服务器...
  - travis_wait 30 scp -o stricthostkeychecking=no -rC ./* root@${G_HOST}:/root/provenr-local/blog