language: node_js  #设置语言
node_js: stable  # 设置node 版本

#cache:
#  apt: true
#  directories:
#    - node_modules
#    - CNAME
env:
  global:
  - GH_REF=github.com/Provenr/provenr.github.io.git   # 设置 github 项目仓库地址
  - GH_username=liuyangning                         # 设置 github 用名
  - GH_useremail=web_lyn@163.com

git:
  submodules: false

before_install:
  - export TZ='Asia/Beijing' # 更改时区
  - npm install hexo-cli -g

install:
  - npm install

before_script:
  - echo 清空缓存静态文件
  - hexo clean  # 清除
  - echo 生成静态文件...
  - hexo g  # 生成
  - cd ./public

script:
  - echo 开始部署...
  - git init
  - git config --global user.name "${GH_username}"  #修改name
  - git config --global user.email "${GH_useremail}"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

# before_cache:
# after_success:
# after_failure:
# before_deploy:
# deploy:
# after_deploy:

after_script:
  - echo 部署完成！
branches:
  only:
    - master  # 只监控master分支，可根据自己情况设置
