language: node_js
node_js:
  - 12

cache:
  apt: true
  directories:
    - node_modules

before_install:
#  - echo 切换yarn淘宝源
#  - yarn config set registry https://registry.npm.taobao.org/
  - npm install hexo -g

install:
  - echo 安装hexo相关环境
  - npm install

before_script:
  - echo 正在清空缓存静态文件...
  - hexo clean                      # 清除缓存静态文件
  - echo 正在生成静态文件...
  - hexo generate                   # 生成静态文件
  - cd ./public
  - ls -l

script:
  - echo 开始部署...
  - git init
  - git config --global user.name "${GH_username}"                          # 修改name
  - git config --global user.email "${GH_useremail}"                        # 修改email
  - git add .
  - git commit -m "update auto by travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  # GH_TOKEN是在Travis中配置token的名稱

after_script:
  - echo 部署完成！

branches:
  only:
    - master                                                                # 只監測master分支，master是我的博客源碼分支的名稱，可根據自己情況設置
env:
  global:
    - GH_REF=github.com/Provenr/Provenr.github.io.git       # 设置 github 项目仓库地址
    - GH_username=liuyangning                          # 设置 github 用户名
    - GH_useremail=web_lyn@163.com