language: node_js  #設置語言

node_js: stable  #設置相應的版本

cache:
  apt: true
  directories:
    - node_modules # 緩存不經常更改的內容
    - CNAME

before_install:
  # - export TZ='Asia/Beijing' # 更改时区
  - echo 安装hexo相关环境...
  - npm install hexo-cli -g
  # - chmod +x ./publish-to-gh-pages.sh  # 为shell文件添加可执行权限

install:
  # - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - npm install

before_script:
  - echo 清空缓存静态文件
  - hexo clean  # 清除
  - echo 生成静态文件...
  - hexo g  # 生成


script:
  - echo 开始部署...
  - git init
  - git config --global user.name "${GH_username}"  #修改name
  - git config --global user.email "${GH_useremail}"  #修改email
  - git add .
  - git commit -m "ravis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

# before_cache:
# after_success:
# after_failure:
# before_deploy:
# deploy:
# after_deploy:

after_script:
  - echo 部署完成！
branches:
  only:
    - master #只監測master分支，master是我的博客源碼分支的名稱，可根據自己情況設置
env:
  global:
    - GH_REF: github.com/Provenr/provenr.github.io.git   # 设置 github 项目仓库地址
    - GH_username:  liuyangning                         # 设置 github 用名
    - GH_useremail: web_lyn@163.com